#!/bin/sh
#
# Powertune Start

start() {
/usr/bin/PowertuneQMLGui &
}
stop() {
killall PowertuneQMLGui
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
     *)
        echo "Usage: $0 {start|stop|restart}"
esac

exit 0
